"""create sales tables

Revision ID: 2e30d64dd388
Revises: ee7da7cae44d
Create Date: 2026-08-02 23:28:29.356591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '2e30d64dd388'
down_revision: Union[str, Sequence[str], None] = 'ee7da7cae44d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


sale_status_enum = postgresql.ENUM(
    "completed",
    "cancelled",
    name="sale_status",
    create_type=False,
)

sale_item_type_enum = postgresql.ENUM(
    "product",
    "service",
    name="sale_item_type",
    create_type=False,
)

sale_payment_method_enum = postgresql.ENUM(
    "cash",
    "card",
    "transfer",
    "other",
    name="sale_payment_method",
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()

    sale_status_enum.create(
        bind,
        checkfirst=True,
    )
    sale_item_type_enum.create(
        bind,
        checkfirst=True,
    )
    sale_payment_method_enum.create(
        bind,
        checkfirst=True,
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('cash_session_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('cancelled_by_user_id', sa.UUID(), nullable=True),
    sa.Column('inventory_movement_id', sa.UUID(), nullable=True),
    sa.Column('cash_transaction_id', sa.UUID(), nullable=True),
    sa.Column('cancellation_inventory_movement_id', sa.UUID(), nullable=True),
    sa.Column('cancellation_cash_transaction_id', sa.UUID(), nullable=True),
    sa.Column('sale_number', sa.String(length=100), nullable=False),
    sa.Column('status', sale_status_enum, server_default='completed', nullable=False),
    sa.Column('company_name', sa.String(length=150), nullable=False),
    sa.Column('company_tax_id', sa.String(length=30), nullable=False),
    sa.Column('company_email', sa.String(length=255), nullable=True),
    sa.Column('company_phone', sa.String(length=30), nullable=True),
    sa.Column('customer_name', sa.String(length=201), nullable=True),
    sa.Column('customer_document', sa.String(length=50), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('customer_phone', sa.String(length=30), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), server_default='0.00', nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), server_default='0.00', nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('change_amount', sa.Numeric(precision=14, scale=2), server_default='0.00', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=500), nullable=True),
    sa.Column('sold_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            (\n                status = 'completed'\n                AND cancelled_by_user_id IS NULL\n                AND cancelled_at IS NULL\n                AND cancellation_reason IS NULL\n            )\n            OR\n            (\n                status = 'cancelled'\n                AND cancelled_by_user_id IS NOT NULL\n                AND cancelled_at IS NOT NULL\n                AND cancellation_reason IS NOT NULL\n                AND char_length(trim(cancellation_reason)) > 0\n            )\n            ", name='ck_sales_status_cancellation_data'),
    sa.CheckConstraint('change_amount >= 0', name='ck_sales_change_non_negative'),
    sa.CheckConstraint('char_length(trim(company_name)) > 0', name='ck_sales_company_name_not_blank'),
    sa.CheckConstraint('char_length(trim(company_tax_id)) > 0', name='ck_sales_company_tax_id_not_blank'),
    sa.CheckConstraint('char_length(trim(sale_number)) > 0', name='ck_sales_number_not_blank'),
    sa.CheckConstraint('discount_amount <= subtotal', name='ck_sales_discount_not_greater_than_subtotal'),
    sa.CheckConstraint('discount_amount >= 0', name='ck_sales_discount_non_negative'),
    sa.CheckConstraint('paid_amount > 0', name='ck_sales_paid_positive'),
    sa.CheckConstraint('subtotal > 0', name='ck_sales_subtotal_positive'),
    sa.CheckConstraint('tax_amount >= 0', name='ck_sales_tax_non_negative'),
    sa.CheckConstraint('total_amount > 0', name='ck_sales_total_positive'),
    sa.ForeignKeyConstraint(['cancellation_cash_transaction_id'], ['cash_transactions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cancellation_inventory_movement_id'], ['inventory_movements.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cancelled_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cash_session_id'], ['cash_sessions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cash_transaction_id'], ['cash_transactions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inventory_movement_id'], ['inventory_movements.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cancellation_cash_transaction_id'),
    sa.UniqueConstraint('cancellation_inventory_movement_id'),
    sa.UniqueConstraint('cash_transaction_id'),
    sa.UniqueConstraint('company_id', 'sale_number', name='uq_sales_company_number'),
    sa.UniqueConstraint('inventory_movement_id')
    )
    op.create_index(op.f('ix_sales_cancelled_at'), 'sales', ['cancelled_at'], unique=False)
    op.create_index(op.f('ix_sales_cancelled_by_user_id'), 'sales', ['cancelled_by_user_id'], unique=False)
    op.create_index(op.f('ix_sales_cash_session_id'), 'sales', ['cash_session_id'], unique=False)
    op.create_index('ix_sales_company_customer_sold', 'sales', ['company_id', 'customer_id', 'sold_at'], unique=False)
    op.create_index(op.f('ix_sales_company_id'), 'sales', ['company_id'], unique=False)
    op.create_index('ix_sales_company_session_sold', 'sales', ['company_id', 'cash_session_id', 'sold_at'], unique=False)
    op.create_index('ix_sales_company_status_sold', 'sales', ['company_id', 'status', 'sold_at'], unique=False)
    op.create_index(op.f('ix_sales_created_by_user_id'), 'sales', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_sales_customer_id'), 'sales', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sales_sale_number'), 'sales', ['sale_number'], unique=False)
    op.create_index(op.f('ix_sales_sold_at'), 'sales', ['sold_at'], unique=False)
    op.create_index(op.f('ix_sales_status'), 'sales', ['status'], unique=False)
    op.create_table('sale_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sale_id', sa.UUID(), nullable=False),
    sa.Column('item_type', sale_item_type_enum, nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('service_id', sa.UUID(), nullable=True),
    sa.Column('item_code', sa.String(length=100), nullable=True),
    sa.Column('item_name', sa.String(length=150), nullable=False),
    sa.Column('item_description', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=20), server_default='unit', nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=2), server_default='0.00', nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), server_default='0.00', nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), server_default='0.00', nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), server_default='0.00', nullable=False),
    sa.Column('line_subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            (\n                item_type = 'product'\n                AND product_id IS NOT NULL\n                AND service_id IS NULL\n            )\n            OR\n            (\n                item_type = 'service'\n                AND service_id IS NOT NULL\n                AND product_id IS NULL\n            )\n            ", name='ck_sale_details_item_reference'),
    sa.CheckConstraint('char_length(trim(item_name)) > 0', name='ck_sale_details_name_not_blank'),
    sa.CheckConstraint('discount_amount <= line_subtotal', name='ck_sale_details_discount_not_greater_than_subtotal'),
    sa.CheckConstraint('discount_amount >= 0', name='ck_sale_details_discount_non_negative'),
    sa.CheckConstraint('line_subtotal >= 0', name='ck_sale_details_subtotal_non_negative'),
    sa.CheckConstraint('line_total >= 0', name='ck_sale_details_total_non_negative'),
    sa.CheckConstraint('quantity > 0', name='ck_sale_details_quantity_positive'),
    sa.CheckConstraint('tax_amount >= 0', name='ck_sale_details_tax_non_negative'),
    sa.CheckConstraint('tax_rate >= 0 AND tax_rate <= 100', name='ck_sale_details_tax_rate_valid'),
    sa.CheckConstraint('unit_cost >= 0', name='ck_sale_details_unit_cost_non_negative'),
    sa.CheckConstraint('unit_price >= 0', name='ck_sale_details_unit_price_non_negative'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_details_item_type'), 'sale_details', ['item_type'], unique=False)
    op.create_index('ix_sale_details_product_created', 'sale_details', ['product_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_sale_details_product_id'), 'sale_details', ['product_id'], unique=False)
    op.create_index(op.f('ix_sale_details_sale_id'), 'sale_details', ['sale_id'], unique=False)
    op.create_index('ix_sale_details_sale_type', 'sale_details', ['sale_id', 'item_type'], unique=False)
    op.create_index('ix_sale_details_service_created', 'sale_details', ['service_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_sale_details_service_id'), 'sale_details', ['service_id'], unique=False)
    op.create_table('sale_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sale_id', sa.UUID(), nullable=False),
    sa.Column('payment_method', sale_payment_method_enum, nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tendered_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('reference', sa.String(length=150), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            (\n                payment_method = 'cash'\n                AND tendered_amount IS NOT NULL\n                AND tendered_amount >= amount\n            )\n            OR\n            (\n                payment_method <> 'cash'\n                AND tendered_amount IS NULL\n            )\n            ", name='ck_sale_payments_tendered_amount'),
    sa.CheckConstraint('amount > 0', name='ck_sale_payments_amount_positive'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_payments_payment_method'), 'sale_payments', ['payment_method'], unique=False)
    op.create_index('ix_sale_payments_reference', 'sale_payments', ['reference'], unique=False)
    op.create_index(op.f('ix_sale_payments_sale_id'), 'sale_payments', ['sale_id'], unique=False)
    op.create_index('ix_sale_payments_sale_method', 'sale_payments', ['sale_id', 'payment_method'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sale_payments_sale_method', table_name='sale_payments')
    op.drop_index(op.f('ix_sale_payments_sale_id'), table_name='sale_payments')
    op.drop_index('ix_sale_payments_reference', table_name='sale_payments')
    op.drop_index(op.f('ix_sale_payments_payment_method'), table_name='sale_payments')
    op.drop_table('sale_payments')
    op.drop_index(op.f('ix_sale_details_service_id'), table_name='sale_details')
    op.drop_index('ix_sale_details_service_created', table_name='sale_details')
    op.drop_index('ix_sale_details_sale_type', table_name='sale_details')
    op.drop_index(op.f('ix_sale_details_sale_id'), table_name='sale_details')
    op.drop_index(op.f('ix_sale_details_product_id'), table_name='sale_details')
    op.drop_index('ix_sale_details_product_created', table_name='sale_details')
    op.drop_index(op.f('ix_sale_details_item_type'), table_name='sale_details')
    op.drop_table('sale_details')
    op.drop_index(op.f('ix_sales_status'), table_name='sales')
    op.drop_index(op.f('ix_sales_sold_at'), table_name='sales')
    op.drop_index(op.f('ix_sales_sale_number'), table_name='sales')
    op.drop_index(op.f('ix_sales_customer_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_created_by_user_id'), table_name='sales')
    op.drop_index('ix_sales_company_status_sold', table_name='sales')
    op.drop_index('ix_sales_company_session_sold', table_name='sales')
    op.drop_index(op.f('ix_sales_company_id'), table_name='sales')
    op.drop_index('ix_sales_company_customer_sold', table_name='sales')
    op.drop_index(op.f('ix_sales_cash_session_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_cancelled_by_user_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_cancelled_at'), table_name='sales')
    op.drop_table('sales')

    bind = op.get_bind()

    sale_payment_method_enum.drop(
        bind,
        checkfirst=True,
    )
    sale_item_type_enum.drop(
        bind,
        checkfirst=True,
    )
    sale_status_enum.drop(
        bind,
        checkfirst=True,
    )
    # ### end Alembic commands ###
