"""create employees tables

Revision ID: 3c4e8eca58c3
Revises: b6a0166fb947
Create Date: 2026-07-27 15:22:55.033493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c4e8eca58c3'
down_revision: Union[str, Sequence[str], None] = 'b6a0166fb947'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('document_number', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=False),
    sa.Column('salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('commission_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('attendance_code', sa.String(length=30), nullable=True),
    sa.Column('biometric_device_user_id', sa.String(length=100), nullable=True),
    sa.Column('biometric_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('\n            commission_percentage IS NULL\n            OR (\n                commission_percentage >= 0\n                AND commission_percentage <= 100\n            )\n            ', name='ck_employees_commission_percentage'),
    sa.CheckConstraint('salary IS NULL OR salary >= 0', name='ck_employees_salary_non_negative'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'attendance_code', name='uq_employees_company_attendance_code'),
    sa.UniqueConstraint('company_id', 'biometric_device_user_id', name='uq_employees_company_biometric_user'),
    sa.UniqueConstraint('company_id', 'email', name='uq_employees_company_email')
    )
    op.create_index(op.f('ix_employees_attendance_code'), 'employees', ['attendance_code'], unique=False)
    op.create_index(op.f('ix_employees_biometric_device_user_id'), 'employees', ['biometric_device_user_id'], unique=False)
    op.create_index(op.f('ix_employees_company_id'), 'employees', ['company_id'], unique=False)
    op.create_index(op.f('ix_employees_document_number'), 'employees', ['document_number'], unique=False)
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=False)
    op.create_index(op.f('ix_employees_first_name'), 'employees', ['first_name'], unique=False)
    op.create_index(op.f('ix_employees_job_title'), 'employees', ['job_title'], unique=False)
    op.create_index(op.f('ix_employees_last_name'), 'employees', ['last_name'], unique=False)
    op.create_index(op.f('ix_employees_phone'), 'employees', ['phone'], unique=False)
    op.create_table('employee_services',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('employee_id', 'service_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_services')
    op.drop_index(op.f('ix_employees_phone'), table_name='employees')
    op.drop_index(op.f('ix_employees_last_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_job_title'), table_name='employees')
    op.drop_index(op.f('ix_employees_first_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_index(op.f('ix_employees_document_number'), table_name='employees')
    op.drop_index(op.f('ix_employees_company_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_biometric_device_user_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_attendance_code'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
