"""create inventory movement tables

Revision ID: 501c39f48e00
Revises: a874e4dc0d72
Create Date: 2026-08-01 17:26:34.883885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '501c39f48e00'
down_revision: Union[str, Sequence[str], None] = 'a874e4dc0d72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('movement_type', sa.Enum('entry', 'exit', 'adjustment_in', 'adjustment_out', 'consumption', 'return_in', 'return_out', name='inventory_movement_type'), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inventory_movements_company_created', 'inventory_movements', ['company_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_inventory_movements_company_id'), 'inventory_movements', ['company_id'], unique=False)
    op.create_index('ix_inventory_movements_company_type', 'inventory_movements', ['company_id', 'movement_type'], unique=False)
    op.create_index(op.f('ix_inventory_movements_created_at'), 'inventory_movements', ['created_at'], unique=False)
    op.create_index(op.f('ix_inventory_movements_movement_type'), 'inventory_movements', ['movement_type'], unique=False)
    op.create_index(op.f('ix_inventory_movements_reference'), 'inventory_movements', ['reference'], unique=False)
    op.create_index(op.f('ix_inventory_movements_user_id'), 'inventory_movements', ['user_id'], unique=False)
    op.create_table('inventory_movement_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('movement_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('stock_before', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('stock_after', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_inventory_movement_details_quantity_positive'),
    sa.CheckConstraint('stock_after >= 0', name='ck_inventory_movement_details_stock_after_non_negative'),
    sa.CheckConstraint('stock_before >= 0', name='ck_inventory_movement_details_stock_before_non_negative'),
    sa.ForeignKeyConstraint(['movement_id'], ['inventory_movements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movement_id', 'product_id', name='uq_inventory_movement_details_movement_product')
    )
    op.create_index(op.f('ix_inventory_movement_details_movement_id'), 'inventory_movement_details', ['movement_id'], unique=False)
    op.create_index('ix_inventory_movement_details_product_created', 'inventory_movement_details', ['product_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_inventory_movement_details_product_id'), 'inventory_movement_details', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_movement_details_product_id'), table_name='inventory_movement_details')
    op.drop_index('ix_inventory_movement_details_product_created', table_name='inventory_movement_details')
    op.drop_index(op.f('ix_inventory_movement_details_movement_id'), table_name='inventory_movement_details')
    op.drop_table('inventory_movement_details')
    op.drop_index(op.f('ix_inventory_movements_user_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_reference'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_movement_type'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_created_at'), table_name='inventory_movements')
    op.drop_index('ix_inventory_movements_company_type', table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_company_id'), table_name='inventory_movements')
    op.drop_index('ix_inventory_movements_company_created', table_name='inventory_movements')
    op.drop_table('inventory_movements')
    # ### end Alembic commands ###
