"""create suppliers table

Revision ID: 5596c072880d
Revises: 4a31208efde1
Create Date: 2026-08-02 15:24:35.646567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5596c072880d'
down_revision: Union[str, Sequence[str], None] = '4a31208efde1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tax_id', sa.String(length=50), nullable=False),
    sa.Column('business_name', sa.String(length=150), nullable=False),
    sa.Column('trade_name', sa.String(length=150), nullable=True),
    sa.Column('contact_name', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("btrim(business_name) <> ''", name='ck_suppliers_business_name_not_blank'),
    sa.CheckConstraint("btrim(tax_id) <> ''", name='ck_suppliers_tax_id_not_blank'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'tax_id', name='uq_suppliers_company_tax_id')
    )
    op.create_index('ix_suppliers_company_active', 'suppliers', ['company_id', 'is_active'], unique=False)
    op.create_index('ix_suppliers_company_business_name', 'suppliers', ['company_id', 'business_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_suppliers_company_business_name', table_name='suppliers')
    op.drop_index('ix_suppliers_company_active', table_name='suppliers')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
