"""create company settings

Revision ID: 688dcd2c9da5
Revises: d9f2a4b6c8e1
Create Date: 2026-08-24 17:08:26.990038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '688dcd2c9da5'
down_revision: Union[str, Sequence[str], None] = 'd9f2a4b6c8e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('updated_by_user_id', sa.UUID(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country_code', sa.String(length=2), server_default='CO', nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('currency_code', sa.String(length=3), server_default='COP', nullable=False),
    sa.Column('currency_symbol', sa.String(length=10), server_default='$', nullable=False),
    sa.Column('tax_name', sa.String(length=50), server_default='IVA', nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('prices_include_tax', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sale_prefix', sa.String(length=20), server_default='VTA', nullable=False),
    sa.Column('next_sale_number', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('sale_number_padding', sa.Integer(), server_default=sa.text('6'), nullable=False),
    sa.Column('timezone', sa.String(length=100), server_default='America/Bogota', nullable=False),
    sa.Column('locale', sa.String(length=20), server_default='es_CO', nullable=False),
    sa.Column('date_format', sa.String(length=30), server_default='DD/MM/YYYY', nullable=False),
    sa.Column('time_format', sa.String(length=10), server_default='24h', nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('primary_color', sa.String(length=7), server_default='#17324D', nullable=False),
    sa.Column('secondary_color', sa.String(length=7), server_default='#2F918C', nullable=False),
    sa.Column('appointment_slot_minutes', sa.Integer(), server_default=sa.text('30'), nullable=False),
    sa.Column('allow_appointment_overlap', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('low_stock_threshold', sa.Numeric(precision=12, scale=3), server_default=sa.text('5.000'), nullable=False),
    sa.Column('require_customer_for_sale', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('send_email_receipts', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('send_whatsapp_receipts', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('appointment_slot_minutes >= 5 AND appointment_slot_minutes <= 240', name='ck_company_settings_appointment_slot'),
    sa.CheckConstraint('low_stock_threshold >= 0', name='ck_company_settings_low_stock_threshold'),
    sa.CheckConstraint('next_sale_number >= 1', name='ck_company_settings_next_sale_number'),
    sa.CheckConstraint('sale_number_padding >= 1 AND sale_number_padding <= 12', name='ck_company_settings_sale_number_padding'),
    sa.CheckConstraint('tax_rate >= 0 AND tax_rate <= 100', name='ck_company_settings_tax_rate'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', name='uq_company_settings_company_id')
    )
    op.create_index(op.f('ix_company_settings_updated_by_user_id'), 'company_settings', ['updated_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_settings_updated_by_user_id'), table_name='company_settings')
    op.drop_table('company_settings')
    # ### end Alembic commands ###
