"""create inventory tables

Revision ID: a874e4dc0d72
Revises: 45ca6ff05c8a
Create Date: 2026-08-01 14:16:08.593769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a874e4dc0d72'
down_revision: Union[str, Sequence[str], None] = '45ca6ff05c8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_product_categories_company_name')
    )
    op.create_index('ix_product_categories_company_active', 'product_categories', ['company_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_product_categories_company_id'), 'product_categories', ['company_id'], unique=False)
    op.create_index(op.f('ix_product_categories_is_active'), 'product_categories', ['is_active'], unique=False)
    op.create_index(op.f('ix_product_categories_name'), 'product_categories', ['name'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('current_stock', sa.Numeric(precision=14, scale=3), server_default='0.000', nullable=False),
    sa.Column('minimum_stock', sa.Numeric(precision=14, scale=3), server_default='0.000', nullable=False),
    sa.Column('maximum_stock', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('unit', sa.String(length=20), server_default='unit', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('current_stock >= 0', name='ck_products_current_stock_non_negative'),
    sa.CheckConstraint('maximum_stock IS NULL OR maximum_stock >= minimum_stock', name='ck_products_maximum_stock_valid'),
    sa.CheckConstraint('minimum_stock >= 0', name='ck_products_minimum_stock_non_negative'),
    sa.CheckConstraint('purchase_price >= 0', name='ck_products_purchase_price_non_negative'),
    sa.CheckConstraint('sale_price >= 0', name='ck_products_sale_price_non_negative'),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'barcode', name='uq_products_company_barcode'),
    sa.UniqueConstraint('company_id', 'code', name='uq_products_company_code')
    )
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=False)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_code'), 'products', ['code'], unique=False)
    op.create_index('ix_products_company_active', 'products', ['company_id', 'is_active'], unique=False)
    op.create_index('ix_products_company_category', 'products', ['company_id', 'category_id'], unique=False)
    op.create_index(op.f('ix_products_company_id'), 'products', ['company_id'], unique=False)
    op.create_index('ix_products_company_name', 'products', ['company_id', 'name'], unique=False)
    op.create_index(op.f('ix_products_is_active'), 'products', ['is_active'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_is_active'), table_name='products')
    op.drop_index('ix_products_company_name', table_name='products')
    op.drop_index(op.f('ix_products_company_id'), table_name='products')
    op.drop_index('ix_products_company_category', table_name='products')
    op.drop_index('ix_products_company_active', table_name='products')
    op.drop_index(op.f('ix_products_code'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_product_categories_name'), table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_is_active'), table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_company_id'), table_name='product_categories')
    op.drop_index('ix_product_categories_company_active', table_name='product_categories')
    op.drop_table('product_categories')
    # ### end Alembic commands ###
